export declare const messageIdMap: {
    ban_base_href_assignments: string;
    ban_document_execcommand: string;
    ban_document_write_calls: string;
    ban_document_writeln_calls: string;
    ban_domparser_parsefromstring: string;
    ban_element_innerhtml_assignments: string;
    ban_element_insertadjacenthtml: string;
    ban_element_outerhtml_assignments: string;
    ban_element_setattribute: string;
    ban_eval_calls: string;
    ban_function_calls: string;
    ban_iframe_srcdoc_assignments: string;
    ban_object_data_assignments: string;
    ban_range_createcontextualfragment: string;
    ban_script_appendchild_calls: string;
    ban_script_content_assignments: string;
    ban_script_src_assignments: string;
    ban_serviceworkercontainer_register: string;
    ban_shared_worker_calls: string;
    ban_trustedtypes_createpolicy: string;
    ban_window_stringfunctiondef: string;
    ban_worker_calls: string;
    ban_worker_importscripts: string;
    ban_legacy_conversions: string;
    ban_reviewed_conversions: string;
};
export type TrustedTypeCheckMessageId = keyof typeof messageIdMap;
export declare function tsetseMessageToMessageId(tsetseMessage: string): TrustedTypeCheckMessageId | undefined;
